//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LaserDeicing.rc
//
#define IDCANCEL                        2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LaserDeicing_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDD_DLG_PTZ_CRUISE              130
#define IDC_ROI_WIDTH_EDIT              130
#define IDD_IMAGE_PREPROCESSING_DIALOG  131
#define IDI_ICON1                       137
#define IDD_IMAGE_SEGMENTATION_DIALOG   154
#define IDD_IMAGE_EDGEEXTRACTION_DIALOG 155
#define IDD_DLG_DO_TEST                 313
#define IDD_DLG_SetPtzPos               313
#define IDC_STATIC_PLAY                 1000
#define IDC_BTN_EXIT                    1001
#define IDC_BUTTON_PLAY                 1002
#define IDC_BUTTON_RECORD               1003
#define IDC_TREE_CHAN                   1004
#define IDC_COMBO_PTZ_SPEED             1005
#define IDC_BUTTON_CAPTURE              1006
#define IDC_IMSHOW_2                    1007
#define IDC_COMBO_PRESET                1008
#define IDC_ROI_X_EDIT                  1008
#define IDC_IPADDRESS_DEV               1009
#define IDC_GRAY_BUTTON                 1009
#define IDC_EDIT_PORT                   1010
#define IDC_ROBERTS_BUTTON              1010
#define IDC_EDIT_USER                   1011
#define IDC_EDIT_PWD                    1012
#define IDC_ROIA_Y_EDIT                 1012
#define IDC_BUTTON_LOGIN                1013
#define IDC_ROI_HEIGHT_EDIT             1013
#define IDC_BUTTON_PRESET_GOTO          1014
#define IDC_SRC_IMSHOW                  1014
#define IDC_BUTTON_PRESET_SET           1015
#define IDC_IMAGESTRETCHING_BUTTON      1015
#define IDC_BUTTON_PRESET_DEL           1016
#define IDC_GAUSSIAN_BUTTON             1016
#define IDC_ERODE_BUTTON                1016
#define IDC_COMBO_SEQ                   1017
#define IDC_BLUR_BUTTON                 1017
#define IDC_DILATE_BUTTON               1017
#define IDC_OTUS_BUTTON                 1017
#define IDC_BUTTON_SEQ_GOTO             1018
#define IDC_EQUALIZE_BUTTON             1018
#define IDC_ADAPTIVE_BUTTON             1018
#define IDC_BTN_PTZ_LEFT                1019
#define IDC_MEDIANBLUR_BUTTON           1019
#define IDC_CONTOURS_BUTTON             1019
#define IDC_BTN_PTZ_DOWN                1020
#define IDC_BILATERALFILTER_BUTTON      1020
#define IDC_DST_CONTOURS_BUTTON         1020
#define IDC_BTN_PTZ_UP                  1021
#define IDC_CALC_HIST_BUTTON            1021
#define IDC_BTN_PTZ_RIGHT               1022
#define IDC_COMPENSATION_BUTTON         1022
#define IDC_BTN_ZOOM_IN                 1023
#define IDC_IMAGEPREPROCESSING_CLOSE_FILE 1023
#define IDC_LAPLACE_BUTTON              1023
#define IDC_BTN_FOCUS_NEAR              1024
#define IDC_IMAGEPREPROCESSONG_OPEN_FILE 1024
#define IDC_BTN_IRIS_OPEN               1025
#define IDC_DST_IMSHOW                  1025
#define IDC_BTN_ZOOM_OUT                1026
#define IDC_ROI_BUTTON                  1026
#define IDC_EDGEEXRACTION_OPEN_FILE     1026
#define IDC_BTN_FOCUS_FAR               1027
#define IDC_BTN_IRIS_CLOSE              1028
#define IDC_BUTTON_SEQ_SET              1029
#define IDC_BUTTON_TRACK_START          1030
#define IDC_BUTTON_TRACK_STOP           1031
#define IDC_BUTTON_TRACK_RUN            1032
#define IDC_BTN_PTZ_UPLEFT              1033
#define IDC_BTN_PTZ_UPRIGHT             1034
#define IDC_BTN_PTZ_DOWNLEFT            1035
#define IDC_BTN_PTZ_DOWNRIGHT           1036
#define IDC_BTN_LIGHT_PWRON             1037
#define IDC_BTN_WIPER_PWRON             1038
#define IDC_BTN_FAN_PWRON               1039
#define IDC_BTN_HEATER_PWRON            1040
#define IDC_BTN_AUX_PWRON               1041
#define IDC_BTN_PTZ_AUTO                1042
#define IDC_BTN_AUX_PWRON2              1043
#define IDC_BLUR_EDIT                   1043
#define IDC_COMBO_PIC_TYPE              1044
#define IDC_MEDIAN_EDIT                 1044
#define IDC_STRUCT_ELEMENT_EDIT         1044
#define IDC_COMBO_JPG_SIZE              1045
#define IDC_GAUSSIAN_EDIT               1045
#define IDC_HIGHTHRESHOLD_EDIT          1045
#define IDC_COMBO_JPG_QUALITY           1046
#define IDC_BILATERAL_EDIT              1046
#define IDC_ERODE_EDIT                  1046
#define IDC_STATIC_JPGPARA              1047
#define IDC_DILATE_EDIT                 1047
#define IDC_BLOCKSIZE_EDIT              1047
#define IDC_BUTTON1                     1048
#define IDC_MORPHOLOGY_COMBO            1048
#define IDC_CONTOUR_AREA_THRESHOLD_EDIT 1048
#define IDC_EDGEEXRACTION_CLOSE_FILE    1049
#define IDC_IMSHOW_3                    1049
#define IDC_SOBEL_BUTTON                1050
#define IDC_CONTOURS_NUMBER_EDIT        1050
#define IDC_IMSHOW_4                    1050
#define IDC_SRC_IMSHOW1                 1051
#define IDC_EDIT_POINT                  1051
#define IDC_DST_IMSHOW1                 1052
#define IDC_EDIT_DISTANCE               1052
#define IDC_LOWTHRESHOLD_EDIT           1053
#define IDC_EDIT_P2                     1053
#define IDC_PREWITT_BUTTON              1054
#define IDC_EDIT_P1                     1054
#define IDC_CANNY_BUTTON                1055
#define IDC_INFO                        1055
#define IDC_BUTTON_INFO_CLC             1056
#define IDC_SetPtzPos_BUTTON            1057
#define IDC_THRESHOLD_EDIT              1058
#define IDC_THRESHOLD_TYPE_COMBO        1059
#define IDC_THRESHOLD_BUTTON            1060
#define IDC_THRESHOLD_ADAPTIVE_METHOD_COMBO 1061
#define IDC_CONTOURS_MODE_COMBO         1062
#define IDC_CONTOURS_METHOD_COMBO       1063
#define IDC_OPENFILE_BUTTON1            1063
#define IDC_CLINK_ON_BUTTON             1065
#define IDC_STATIC2                     1067
#define IDC_STATIC3                     1068
#define IDC_STATIC4                     1069
#define IDC_STATIC5                     1070
#define IDC_STATIC9                     1071
#define IDC_STATIC11                    1076
#define IDC_STATIC12                    1077
#define IDC_STATIC13                    1078
#define IDC_STATIC14                    1079
#define IDC_IMAGE_PREPROCESSING_BUTTON  1082
#define IDC_IMAGE_SEGMENTATION_BUTTON   1084
#define IDC_COMBO_CRUISE_ROUTE          1085
#define IDC_IMAGE_EDGEEXTRACTION_BUTTON 1085
#define IDC_UPDATE_BUTTON               1086
#define IDC_COMBO_CRUISE_POINT          1087
#define IDC_COMBO_CRUISE_PRESET         1088
#define IDC_COMBO_CRUISE_TIME           1089
#define IDC_COMBO_CRUISE_SPEED          1090
#define IDC_EDIT_PARA1                  1102
#define IDC_EDIT_PARA2                  1103
#define IDC_EDIT_PARA3                  1104
#define IDC_BUTTON_ADD                  1105
#define IDC_BUTTON_DEL                  1106
#define IDC_COMBO_PARA1                 1181
#define IDC_STATIC_CRUISE               1320
#define IDC_SetPtzPos                   1451
#define IDC_STATIC6                     1501
#define IDC_STATIC7                     1502
#define IDC_STATIC8                     1503

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
